include:
  - component: $CI_SERVER_FQDN/components/containers-builder/build@0.7.2
    inputs:
      rules:
        # If a tag is present use it instead of the commit sha
        - if: $CI_COMMIT_TAG
          variables:
            BUILD_IMAGE_TAG: $CI_COMMIT_TAG
        - when: always
      image-name: ckan-frontend
      image-tag: ${CI_COMMIT_SHORT_SHA}

stages:
  - build

variables:
  GIT_SUBMODULE_STRATEGY: normal
  BUILD_IMAGE_NAME: ckan-frontend
  BUILD_IMAGE_TAG: ${CI_COMMIT_SHORT_SHA}
